### ISSUE TITLE
error with poolRuns

### ISSUE THREAD

**Issue by jpoell** [ccagc/QDNAseq#112]
The poolRuns function now produces an error due to matrixStats::colMeans2 requiring a matrix, whereas the inputted phenoData is an annotated data frame. It was able to fix it with by assigning a modified version of poolRuns in my local environment. While I don't expect many users use poolRuns, I think it would be good to fix this nonetheless.
Cheers, 
Jos

**Comment by HenrikBengtsson** [comment]
Thanks for reporting. This looks like a bug to me.  I was first confused that this hasn't been caught yet, because we do have `example("poolRuns", package = "QDNAseq")` that calls `poolRuns()`.  But, it turns out that that example never reaches the problematic code:

https://github.com/ccagc/QDNAseq/blob/41d4da2458593272964ce2121dc8df1b38f78bc6/R/poolRuns.R#L96-L97

Instead, it returns early on at:

https://github.com/ccagc/QDNAseq/blob/41d4da2458593272964ce2121dc8df1b38f78bc6/R/poolRuns.R#L53-L57


I'll try to fix.

**Comment by HenrikBengtsson** [comment]
Would you mind sharing your local patch?

**Comment by jpoell** [comment]
Sure, no problem!

**Comment by HenrikBengtsson** [comment]
> I applied the fix from Jos already, and it seems to work

I'm waiting for that one

**Comment by HenrikBengtsson** [comment]
> Sure, no problem!

@jpoell, we never received your patch here.  Not sure how @briarj got a hand of it.

**Comment by HenrikBengtsson** [comment]
Fix in QDNAseq 1.41.2, that should soon be available in the Bioc devel branch.
