### ISSUE TITLE
Syncing with Bioconductor Git repository

### ISSUE THREAD

**Issue by HenrikBengtsson** [ccagc/QDNAseq#64]
# Issue

This Git repository is out of sync with the Bioconductor Git repository, e.g. the package version here is [1.11.2](https://github.com/ccagc/QDNAseq/blob/8fc576d54f82e853ba3559a43c6e22d3bd06b3ab/DESCRIPTION#L2) whereas the Bioc release version is [1.20.0](http://master.bioconductor.org/packages/release/bioc/html/QDNAseq.html) and the Bioc develop version is 1.21.0.

The fact that it's out of sync makes me wary about submitting PRs etc.

# Suggestion

https://www.bioconductor.org/developers/how-to/git/

PS. I can help setting this up, and proposing a process of keeping it in sync, but then I'd need permissions to push directly to this GitHub repos.

**Comment by ilarischeinin** [comment]
I gave you write access.

It would be great if you can help out here. And the timing is actually perfect, as there is one thing* why we'd like to have the package updated before this fall's Bioconductor release. Neither me nor @daoud-sie no longer work in the lab, and I haven't actually being involved with anything Bioconductor for 5 years, so I'm completely out of touch with the current conventions. (Back in my day they still used SVN and the git-svn bridge.)

\* That one thing is that currently `getBinAnnotations()` by [default](https://github.com/ccagc/QDNAseq/blob/8fc576d54f82e853ba3559a43c6e22d3bd06b3ab/R/getBinAnnotations.R#L60) downloads from an S3 bucket (with other options being to load from a local directory or from a Bioconductor annotation package like [QDNAseq.hg19](https://bioconductor.riken.jp/packages/release/data/experiment/html/QDNAseq.hg19.html)). The S3 bucket it points to is my personal one, and because the costs have been pennies per month I haven't bothered with it. But two months ago they jumped to >20€/month because of heavy usage (from Cambridge and Sloan-Kettering). And because of that, I'd like to change the default from my S3 bucket to either a new hosting location, or just local file/annotation package.

**Comment by ilarischeinin** [comment]
Ha! And perfect timing with that too! #67

**Comment by HenrikBengtsson** [comment]
Fixed.  Due to how the Bioconductor repository moved from SVN to Git the history of our git repository (here) and Bioc git had split histories.  Because of this, I had to move the old 'master' branch to 'master-20190830' before I could bring the new 'master' branch in sync with Bioconductor devel.  In order to do this, I had to do a `git push --force`.  People with cloned repositories locally will have to re-clone.
